#!/bin/bash
#SBATCH --job-name=segthor_run
#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --cpus-per-task=16
#SBATCH --time=12:00:00
#SBATCH --output=jobs/logs/%j/out.log

uv run /home/scur0088/project/src/main.py --epochs 50 --dataset.name SEGTHOR
uv run /home/scur0088/project/src/main.py --epochs 50 --dataset.name SEGTHOR --loss dice_ce
uv run /home/scur0088/project/src/main.py --epochs 50 --dataset.name SEGTHOR --noise_prob 0 --noise_level 0
uv run /home/scur0088/project/src/main.py --epochs 50 --dataset.name SEGTHOR --noise_prob 0 --noise_level 0 --loss dice_ce

