batch_size: 8
betas:
  - 0.9
  - 0.999
dataset:
  fold: 0
  name: SEGTHOR
  num_classes: 5
  retains: 5
  seed: 0
  shape:
    - 256
    - 256
debug: false
dest: null
dropout: 0.01
epochs: 20
gpu: true
lr: 0.0005
mode: full
model:
  factor: 2
  kernels: 8
  name: ENet
noise_level: 0.05
noise_prob: 0.5
num_workers: 5
seed: 42
temperature: 1
wandb_watch: false
weight_decay: 0
