dataset:
  name: SEGTHOR_small
  num_classes: 5
  box_size:
    - 64
    - 64
    - 64
  retains: 2
  fold: 0
model:
  name: UNet3D
  is_3d: true
  kernels: 8
  factor: 2
training:
  epochs: 1
  batch_size: 2
  gpu: true
  seed: 42
  loss: ce
  mode: full
runtime:
  num_workers: 4
